"""
Analytica — Reports Service
Pre-built report definitions and data retrieval.
"""

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.domains.reports.schemas import ReportDefinition, ReportsListResponse


# Pre-defined report catalog
REPORT_CATALOG: list[ReportDefinition] = [
    ReportDefinition(
        id="monthly_sales", name="Monthly Sales Report",
        description="Revenue, orders, and AOV aggregated by month.",
        source_table="reporting_sales_summary", category="Sales",
    ),
    ReportDefinition(
        id="category_performance", name="Category Performance Report",
        description="Revenue and order breakdown by product category.",
        source_table="reporting_category_summary", category="Products",
    ),
    ReportDefinition(
        id="state_summary", name="State Revenue Report",
        description="Geographic distribution of revenue, orders, and customers.",
        source_table="reporting_state_summary", category="Geography",
    ),
    ReportDefinition(
        id="customer_summary", name="Customer Lifetime Report",
        description="Customer lifetime revenue, orders, and repeat status.",
        source_table="reporting_customer_summary", category="Customers",
    ),
    ReportDefinition(
        id="seller_summary", name="Seller Performance Report",
        description="Fulfillment volume and total revenue generated by seller.",
        source_table="reporting_seller_summary", category="Sellers",
    ),
]

# Whitelist of allowed tables for the explorer/reports
ALLOWED_TABLES = {r.source_table for r in REPORT_CATALOG}


def get_report_list() -> ReportsListResponse:
    """Return the catalog of available reports."""
    return ReportsListResponse(reports=REPORT_CATALOG)


def get_report_by_id(report_id: str) -> ReportDefinition | None:
    """Lookup a single report by ID."""
    for r in REPORT_CATALOG:
        if r.id == report_id:
            return r
    return None


async def get_report_data(
    session: AsyncSession,
    table_name: str,
    page: int = 1,
    page_size: int = 50,
) -> tuple[list[dict], int]:
    """Fetch paginated data from a reporting table."""
    if table_name not in ALLOWED_TABLES:
        return [], 0

    # Total count
    count_result = await session.execute(text(f"SELECT COUNT(*) FROM {table_name}"))
    total = count_result.scalar() or 0

    # Paginated data
    offset = (page - 1) * page_size
    data_result = await session.execute(
        text(f"SELECT * FROM {table_name} LIMIT :limit OFFSET :offset"),
        {"limit": page_size, "offset": offset},
    )
    rows = [dict(row) for row in data_result.mappings().all()]

    return rows, total
